export const GET_USER_INFO_REQUEST = Symbol('GET_USER_INFO_REQUEST');
export const GET_USER_INFO_SUCCESS = Symbol('GET_USER_INFO_SUCCESS');
export const GET_USER_INFO_FAILURE = Symbol('GET_USER_INFO_FAILURE');
